#cd <directory with Docker file>
#docker build .

#note the id that is output at the end of the build. Use that id in the command to run the container
#docker run -p 1024:1024 -p 9123:9123 -ti <id> bash


FROM python:slim
RUN apt-get update && apt-get -y upgrade \
  && apt-get install -y --no-install-recommends \
    build-essential \
    zlib1g-dev \
    swig \
    git \
    wget \
    procps \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /root

# Install miniconda and needed packages
ENV PATH="/root/miniconda3/bin:${PATH}"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh
RUN conda install conda-build
RUN pip3 install numpy
RUN conda install dill

# Install latest version of WorkQueue
RUN git clone https://github.com/cooperative-computing-lab/cctools cctools-source
WORKDIR cctools-source
RUN ./configure
RUN make
RUN make install
WORKDIR ..
RUN conda develop cctools/lib/python3.9/site-packages
ENV PATH="/root/cctools/bin:${PATH}"

# Install Dadi
RUN git clone https://bitbucket.org/gutenkunstlab/dadi.git
WORKDIR dadi
RUN python3 setup.py develop
RUN conda develop .
WORKDIR ..

# Install dadi-cli
RUN git clone https://github.com/xin-huang/dadi-cli
WORKDIR dadi-cli
RUN python3 setup.py develop
RUN conda develop .
WORKDIR ..
